// Code generated by ent, DO NOT EDIT.

package promptresponse

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the promptresponse type in the database.
	Label = "prompt_response"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResponse holds the string denoting the response field in the database.
	FieldResponse = "response"
	// FieldIsAnswered holds the string denoting the is_answered field in the database.
	FieldIsAnswered = "is_answered"
	// Table holds the table name of the promptresponse in the database.
	Table = "prompt_responses"
)

// Columns holds all SQL columns for promptresponse fields.
var Columns = []string{
	FieldID,
	FieldResponse,
	FieldIsAnswered,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsAnswered holds the default value on creation for the "is_answered" field.
	DefaultIsAnswered bool
)

// OrderOption defines the ordering options for the PromptResponse queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResponse orders the results by the response field.
func ByResponse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponse, opts...).ToFunc()
}

// ByIsAnswered orders the results by the is_answered field.
func ByIsAnswered(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAnswered, opts...).ToFunc()
}
