// Code generated by ent, DO NOT EDIT.

package promptrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mateusap1/promptq/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLTE(FieldID, id))
}

// Identifier applies equality check predicate on the "identifier" field. It's identical to IdentifierEQ.
func Identifier(v uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldIdentifier, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldPrompt, v))
}

// IsQueued applies equality check predicate on the "is_queued" field. It's identical to IsQueuedEQ.
func IsQueued(v bool) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldIsQueued, v))
}

// IsAnswered applies equality check predicate on the "is_answered" field. It's identical to IsAnsweredEQ.
func IsAnswered(v bool) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldIsAnswered, v))
}

// CreateDate applies equality check predicate on the "create_date" field. It's identical to CreateDateEQ.
func CreateDate(v time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldCreateDate, v))
}

// IdentifierEQ applies the EQ predicate on the "identifier" field.
func IdentifierEQ(v uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldIdentifier, v))
}

// IdentifierNEQ applies the NEQ predicate on the "identifier" field.
func IdentifierNEQ(v uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNEQ(FieldIdentifier, v))
}

// IdentifierIn applies the In predicate on the "identifier" field.
func IdentifierIn(vs ...uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldIn(FieldIdentifier, vs...))
}

// IdentifierNotIn applies the NotIn predicate on the "identifier" field.
func IdentifierNotIn(vs ...uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNotIn(FieldIdentifier, vs...))
}

// IdentifierGT applies the GT predicate on the "identifier" field.
func IdentifierGT(v uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGT(FieldIdentifier, v))
}

// IdentifierGTE applies the GTE predicate on the "identifier" field.
func IdentifierGTE(v uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGTE(FieldIdentifier, v))
}

// IdentifierLT applies the LT predicate on the "identifier" field.
func IdentifierLT(v uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLT(FieldIdentifier, v))
}

// IdentifierLTE applies the LTE predicate on the "identifier" field.
func IdentifierLTE(v uuid.UUID) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLTE(FieldIdentifier, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldContainsFold(FieldPrompt, v))
}

// IsQueuedEQ applies the EQ predicate on the "is_queued" field.
func IsQueuedEQ(v bool) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldIsQueued, v))
}

// IsQueuedNEQ applies the NEQ predicate on the "is_queued" field.
func IsQueuedNEQ(v bool) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNEQ(FieldIsQueued, v))
}

// IsAnsweredEQ applies the EQ predicate on the "is_answered" field.
func IsAnsweredEQ(v bool) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldIsAnswered, v))
}

// IsAnsweredNEQ applies the NEQ predicate on the "is_answered" field.
func IsAnsweredNEQ(v bool) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNEQ(FieldIsAnswered, v))
}

// CreateDateEQ applies the EQ predicate on the "create_date" field.
func CreateDateEQ(v time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldEQ(FieldCreateDate, v))
}

// CreateDateNEQ applies the NEQ predicate on the "create_date" field.
func CreateDateNEQ(v time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNEQ(FieldCreateDate, v))
}

// CreateDateIn applies the In predicate on the "create_date" field.
func CreateDateIn(vs ...time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldIn(FieldCreateDate, vs...))
}

// CreateDateNotIn applies the NotIn predicate on the "create_date" field.
func CreateDateNotIn(vs ...time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldNotIn(FieldCreateDate, vs...))
}

// CreateDateGT applies the GT predicate on the "create_date" field.
func CreateDateGT(v time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGT(FieldCreateDate, v))
}

// CreateDateGTE applies the GTE predicate on the "create_date" field.
func CreateDateGTE(v time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldGTE(FieldCreateDate, v))
}

// CreateDateLT applies the LT predicate on the "create_date" field.
func CreateDateLT(v time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLT(FieldCreateDate, v))
}

// CreateDateLTE applies the LTE predicate on the "create_date" field.
func CreateDateLTE(v time.Time) predicate.PromptRequest {
	return predicate.PromptRequest(sql.FieldLTE(FieldCreateDate, v))
}

// HasPromptResponse applies the HasEdge predicate on the "prompt_response" edge.
func HasPromptResponse() predicate.PromptRequest {
	return predicate.PromptRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PromptResponseTable, PromptResponseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromptResponseWith applies the HasEdge predicate on the "prompt_response" edge with a given conditions (other predicates).
func HasPromptResponseWith(preds ...predicate.PromptResponse) predicate.PromptRequest {
	return predicate.PromptRequest(func(s *sql.Selector) {
		step := newPromptResponseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PromptRequest {
	return predicate.PromptRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PromptRequest {
	return predicate.PromptRequest(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromptRequest) predicate.PromptRequest {
	return predicate.PromptRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromptRequest) predicate.PromptRequest {
	return predicate.PromptRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromptRequest) predicate.PromptRequest {
	return predicate.PromptRequest(sql.NotPredicates(p))
}
