// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PromptRequestsColumns holds the columns for the "prompt_requests" table.
	PromptRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "identifier", Type: field.TypeString, Unique: true},
		{Name: "prompt", Type: field.TypeString},
		{Name: "is_queued", Type: field.TypeBool, Default: false},
	}
	// PromptRequestsTable holds the schema information for the "prompt_requests" table.
	PromptRequestsTable = &schema.Table{
		Name:       "prompt_requests",
		Columns:    PromptRequestsColumns,
		PrimaryKey: []*schema.Column{PromptRequestsColumns[0]},
	}
	// PromptResponsesColumns holds the columns for the "prompt_responses" table.
	PromptResponsesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "response", Type: field.TypeString},
		{Name: "is_answered", Type: field.TypeBool, Default: false},
		{Name: "prompt_request_prompt_response", Type: field.TypeInt, Unique: true},
	}
	// PromptResponsesTable holds the schema information for the "prompt_responses" table.
	PromptResponsesTable = &schema.Table{
		Name:       "prompt_responses",
		Columns:    PromptResponsesColumns,
		PrimaryKey: []*schema.Column{PromptResponsesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "prompt_responses_prompt_requests_prompt_response",
				Columns:    []*schema.Column{PromptResponsesColumns[3]},
				RefColumns: []*schema.Column{PromptRequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PromptRequestsTable,
		PromptResponsesTable,
	}
)

func init() {
	PromptResponsesTable.ForeignKeys[0].RefTable = PromptRequestsTable
}
