// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mateusap1/promptq/ent/predicate"
	"github.com/mateusap1/promptq/ent/promptrequest"
	"github.com/mateusap1/promptq/ent/promptresponse"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePromptRequest  = "PromptRequest"
	TypePromptResponse = "PromptResponse"
)

// PromptRequestMutation represents an operation that mutates the PromptRequest nodes in the graph.
type PromptRequestMutation struct {
	config
	op            Op
	typ           string
	id            *int
	identifier    *string
	prompt        *string
	queued        *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PromptRequest, error)
	predicates    []predicate.PromptRequest
}

var _ ent.Mutation = (*PromptRequestMutation)(nil)

// promptrequestOption allows management of the mutation configuration using functional options.
type promptrequestOption func(*PromptRequestMutation)

// newPromptRequestMutation creates new mutation for the PromptRequest entity.
func newPromptRequestMutation(c config, op Op, opts ...promptrequestOption) *PromptRequestMutation {
	m := &PromptRequestMutation{
		config:        c,
		op:            op,
		typ:           TypePromptRequest,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPromptRequestID sets the ID field of the mutation.
func withPromptRequestID(id int) promptrequestOption {
	return func(m *PromptRequestMutation) {
		var (
			err   error
			once  sync.Once
			value *PromptRequest
		)
		m.oldValue = func(ctx context.Context) (*PromptRequest, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PromptRequest.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPromptRequest sets the old PromptRequest of the mutation.
func withPromptRequest(node *PromptRequest) promptrequestOption {
	return func(m *PromptRequestMutation) {
		m.oldValue = func(context.Context) (*PromptRequest, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PromptRequestMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PromptRequestMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PromptRequestMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PromptRequestMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PromptRequest.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetIdentifier sets the "identifier" field.
func (m *PromptRequestMutation) SetIdentifier(s string) {
	m.identifier = &s
}

// Identifier returns the value of the "identifier" field in the mutation.
func (m *PromptRequestMutation) Identifier() (r string, exists bool) {
	v := m.identifier
	if v == nil {
		return
	}
	return *v, true
}

// OldIdentifier returns the old "identifier" field's value of the PromptRequest entity.
// If the PromptRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PromptRequestMutation) OldIdentifier(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIdentifier is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIdentifier requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIdentifier: %w", err)
	}
	return oldValue.Identifier, nil
}

// ResetIdentifier resets all changes to the "identifier" field.
func (m *PromptRequestMutation) ResetIdentifier() {
	m.identifier = nil
}

// SetPrompt sets the "prompt" field.
func (m *PromptRequestMutation) SetPrompt(s string) {
	m.prompt = &s
}

// Prompt returns the value of the "prompt" field in the mutation.
func (m *PromptRequestMutation) Prompt() (r string, exists bool) {
	v := m.prompt
	if v == nil {
		return
	}
	return *v, true
}

// OldPrompt returns the old "prompt" field's value of the PromptRequest entity.
// If the PromptRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PromptRequestMutation) OldPrompt(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrompt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrompt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrompt: %w", err)
	}
	return oldValue.Prompt, nil
}

// ResetPrompt resets all changes to the "prompt" field.
func (m *PromptRequestMutation) ResetPrompt() {
	m.prompt = nil
}

// SetQueued sets the "queued" field.
func (m *PromptRequestMutation) SetQueued(b bool) {
	m.queued = &b
}

// Queued returns the value of the "queued" field in the mutation.
func (m *PromptRequestMutation) Queued() (r bool, exists bool) {
	v := m.queued
	if v == nil {
		return
	}
	return *v, true
}

// OldQueued returns the old "queued" field's value of the PromptRequest entity.
// If the PromptRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PromptRequestMutation) OldQueued(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQueued is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQueued requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQueued: %w", err)
	}
	return oldValue.Queued, nil
}

// ResetQueued resets all changes to the "queued" field.
func (m *PromptRequestMutation) ResetQueued() {
	m.queued = nil
}

// Where appends a list predicates to the PromptRequestMutation builder.
func (m *PromptRequestMutation) Where(ps ...predicate.PromptRequest) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PromptRequestMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PromptRequestMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PromptRequest, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PromptRequestMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PromptRequestMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PromptRequest).
func (m *PromptRequestMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PromptRequestMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.identifier != nil {
		fields = append(fields, promptrequest.FieldIdentifier)
	}
	if m.prompt != nil {
		fields = append(fields, promptrequest.FieldPrompt)
	}
	if m.queued != nil {
		fields = append(fields, promptrequest.FieldQueued)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PromptRequestMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case promptrequest.FieldIdentifier:
		return m.Identifier()
	case promptrequest.FieldPrompt:
		return m.Prompt()
	case promptrequest.FieldQueued:
		return m.Queued()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PromptRequestMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case promptrequest.FieldIdentifier:
		return m.OldIdentifier(ctx)
	case promptrequest.FieldPrompt:
		return m.OldPrompt(ctx)
	case promptrequest.FieldQueued:
		return m.OldQueued(ctx)
	}
	return nil, fmt.Errorf("unknown PromptRequest field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PromptRequestMutation) SetField(name string, value ent.Value) error {
	switch name {
	case promptrequest.FieldIdentifier:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIdentifier(v)
		return nil
	case promptrequest.FieldPrompt:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrompt(v)
		return nil
	case promptrequest.FieldQueued:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQueued(v)
		return nil
	}
	return fmt.Errorf("unknown PromptRequest field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PromptRequestMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PromptRequestMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PromptRequestMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown PromptRequest numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PromptRequestMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PromptRequestMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PromptRequestMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PromptRequest nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PromptRequestMutation) ResetField(name string) error {
	switch name {
	case promptrequest.FieldIdentifier:
		m.ResetIdentifier()
		return nil
	case promptrequest.FieldPrompt:
		m.ResetPrompt()
		return nil
	case promptrequest.FieldQueued:
		m.ResetQueued()
		return nil
	}
	return fmt.Errorf("unknown PromptRequest field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PromptRequestMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PromptRequestMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PromptRequestMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PromptRequestMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PromptRequestMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PromptRequestMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PromptRequestMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PromptRequest unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PromptRequestMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PromptRequest edge %s", name)
}

// PromptResponseMutation represents an operation that mutates the PromptResponse nodes in the graph.
type PromptResponseMutation struct {
	config
	op            Op
	typ           string
	id            *int
	response      *string
	is_answered   *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PromptResponse, error)
	predicates    []predicate.PromptResponse
}

var _ ent.Mutation = (*PromptResponseMutation)(nil)

// promptresponseOption allows management of the mutation configuration using functional options.
type promptresponseOption func(*PromptResponseMutation)

// newPromptResponseMutation creates new mutation for the PromptResponse entity.
func newPromptResponseMutation(c config, op Op, opts ...promptresponseOption) *PromptResponseMutation {
	m := &PromptResponseMutation{
		config:        c,
		op:            op,
		typ:           TypePromptResponse,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPromptResponseID sets the ID field of the mutation.
func withPromptResponseID(id int) promptresponseOption {
	return func(m *PromptResponseMutation) {
		var (
			err   error
			once  sync.Once
			value *PromptResponse
		)
		m.oldValue = func(ctx context.Context) (*PromptResponse, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PromptResponse.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPromptResponse sets the old PromptResponse of the mutation.
func withPromptResponse(node *PromptResponse) promptresponseOption {
	return func(m *PromptResponseMutation) {
		m.oldValue = func(context.Context) (*PromptResponse, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PromptResponseMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PromptResponseMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PromptResponseMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PromptResponseMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PromptResponse.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetResponse sets the "response" field.
func (m *PromptResponseMutation) SetResponse(s string) {
	m.response = &s
}

// Response returns the value of the "response" field in the mutation.
func (m *PromptResponseMutation) Response() (r string, exists bool) {
	v := m.response
	if v == nil {
		return
	}
	return *v, true
}

// OldResponse returns the old "response" field's value of the PromptResponse entity.
// If the PromptResponse object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PromptResponseMutation) OldResponse(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponse is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponse requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponse: %w", err)
	}
	return oldValue.Response, nil
}

// ResetResponse resets all changes to the "response" field.
func (m *PromptResponseMutation) ResetResponse() {
	m.response = nil
}

// SetIsAnswered sets the "is_answered" field.
func (m *PromptResponseMutation) SetIsAnswered(b bool) {
	m.is_answered = &b
}

// IsAnswered returns the value of the "is_answered" field in the mutation.
func (m *PromptResponseMutation) IsAnswered() (r bool, exists bool) {
	v := m.is_answered
	if v == nil {
		return
	}
	return *v, true
}

// OldIsAnswered returns the old "is_answered" field's value of the PromptResponse entity.
// If the PromptResponse object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PromptResponseMutation) OldIsAnswered(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsAnswered is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsAnswered requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsAnswered: %w", err)
	}
	return oldValue.IsAnswered, nil
}

// ResetIsAnswered resets all changes to the "is_answered" field.
func (m *PromptResponseMutation) ResetIsAnswered() {
	m.is_answered = nil
}

// Where appends a list predicates to the PromptResponseMutation builder.
func (m *PromptResponseMutation) Where(ps ...predicate.PromptResponse) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PromptResponseMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PromptResponseMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PromptResponse, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PromptResponseMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PromptResponseMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PromptResponse).
func (m *PromptResponseMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PromptResponseMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.response != nil {
		fields = append(fields, promptresponse.FieldResponse)
	}
	if m.is_answered != nil {
		fields = append(fields, promptresponse.FieldIsAnswered)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PromptResponseMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case promptresponse.FieldResponse:
		return m.Response()
	case promptresponse.FieldIsAnswered:
		return m.IsAnswered()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PromptResponseMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case promptresponse.FieldResponse:
		return m.OldResponse(ctx)
	case promptresponse.FieldIsAnswered:
		return m.OldIsAnswered(ctx)
	}
	return nil, fmt.Errorf("unknown PromptResponse field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PromptResponseMutation) SetField(name string, value ent.Value) error {
	switch name {
	case promptresponse.FieldResponse:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponse(v)
		return nil
	case promptresponse.FieldIsAnswered:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsAnswered(v)
		return nil
	}
	return fmt.Errorf("unknown PromptResponse field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PromptResponseMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PromptResponseMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PromptResponseMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown PromptResponse numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PromptResponseMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PromptResponseMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PromptResponseMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PromptResponse nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PromptResponseMutation) ResetField(name string) error {
	switch name {
	case promptresponse.FieldResponse:
		m.ResetResponse()
		return nil
	case promptresponse.FieldIsAnswered:
		m.ResetIsAnswered()
		return nil
	}
	return fmt.Errorf("unknown PromptResponse field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PromptResponseMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PromptResponseMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PromptResponseMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PromptResponseMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PromptResponseMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PromptResponseMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PromptResponseMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PromptResponse unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PromptResponseMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PromptResponse edge %s", name)
}
