// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mateusap1/promptq/ent/promptresponse"
)

// PromptResponse is the model entity for the PromptResponse schema.
type PromptResponse struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Response holds the value of the "response" field.
	Response string `json:"response,omitempty"`
	// IsAnswered holds the value of the "is_answered" field.
	IsAnswered   bool `json:"is_answered,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromptResponse) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promptresponse.FieldIsAnswered:
			values[i] = new(sql.NullBool)
		case promptresponse.FieldID:
			values[i] = new(sql.NullInt64)
		case promptresponse.FieldResponse:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromptResponse fields.
func (pr *PromptResponse) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promptresponse.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case promptresponse.FieldResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value.Valid {
				pr.Response = value.String
			}
		case promptresponse.FieldIsAnswered:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_answered", values[i])
			} else if value.Valid {
				pr.IsAnswered = value.Bool
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromptResponse.
// This includes values selected through modifiers, order, etc.
func (pr *PromptResponse) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// Update returns a builder for updating this PromptResponse.
// Note that you need to call PromptResponse.Unwrap() before calling this method if this PromptResponse
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *PromptResponse) Update() *PromptResponseUpdateOne {
	return NewPromptResponseClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the PromptResponse entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *PromptResponse) Unwrap() *PromptResponse {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromptResponse is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *PromptResponse) String() string {
	var builder strings.Builder
	builder.WriteString("PromptResponse(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("response=")
	builder.WriteString(pr.Response)
	builder.WriteString(", ")
	builder.WriteString("is_answered=")
	builder.WriteString(fmt.Sprintf("%v", pr.IsAnswered))
	builder.WriteByte(')')
	return builder.String()
}

// PromptResponses is a parsable slice of PromptResponse.
type PromptResponses []*PromptResponse
