// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mateusap1/promptq/ent/promptrequest"
	"github.com/mateusap1/promptq/ent/promptresponse"
)

// PromptResponse is the model entity for the PromptResponse schema.
type PromptResponse struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Response holds the value of the "response" field.
	Response string `json:"response,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PromptResponseQuery when eager-loading is set.
	Edges                          PromptResponseEdges `json:"edges"`
	prompt_request_prompt_response *int
	selectValues                   sql.SelectValues
}

// PromptResponseEdges holds the relations/edges for other nodes in the graph.
type PromptResponseEdges struct {
	// PromptRequest holds the value of the prompt_request edge.
	PromptRequest *PromptRequest `json:"prompt_request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PromptRequestOrErr returns the PromptRequest value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PromptResponseEdges) PromptRequestOrErr() (*PromptRequest, error) {
	if e.PromptRequest != nil {
		return e.PromptRequest, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: promptrequest.Label}
	}
	return nil, &NotLoadedError{edge: "prompt_request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromptResponse) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promptresponse.FieldID:
			values[i] = new(sql.NullInt64)
		case promptresponse.FieldResponse:
			values[i] = new(sql.NullString)
		case promptresponse.ForeignKeys[0]: // prompt_request_prompt_response
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromptResponse fields.
func (pr *PromptResponse) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promptresponse.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case promptresponse.FieldResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value.Valid {
				pr.Response = value.String
			}
		case promptresponse.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field prompt_request_prompt_response", value)
			} else if value.Valid {
				pr.prompt_request_prompt_response = new(int)
				*pr.prompt_request_prompt_response = int(value.Int64)
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromptResponse.
// This includes values selected through modifiers, order, etc.
func (pr *PromptResponse) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryPromptRequest queries the "prompt_request" edge of the PromptResponse entity.
func (pr *PromptResponse) QueryPromptRequest() *PromptRequestQuery {
	return NewPromptResponseClient(pr.config).QueryPromptRequest(pr)
}

// Update returns a builder for updating this PromptResponse.
// Note that you need to call PromptResponse.Unwrap() before calling this method if this PromptResponse
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *PromptResponse) Update() *PromptResponseUpdateOne {
	return NewPromptResponseClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the PromptResponse entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *PromptResponse) Unwrap() *PromptResponse {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromptResponse is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *PromptResponse) String() string {
	var builder strings.Builder
	builder.WriteString("PromptResponse(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("response=")
	builder.WriteString(pr.Response)
	builder.WriteByte(')')
	return builder.String()
}

// PromptResponses is a parsable slice of PromptResponse.
type PromptResponses []*PromptResponse
