// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mateusap1/promptq/ent/predicate"
	"github.com/mateusap1/promptq/ent/promptrequest"
	"github.com/mateusap1/promptq/ent/promptresponse"
)

// PromptResponseQuery is the builder for querying PromptResponse entities.
type PromptResponseQuery struct {
	config
	ctx               *QueryContext
	order             []promptresponse.OrderOption
	inters            []Interceptor
	predicates        []predicate.PromptResponse
	withPromptRequest *PromptRequestQuery
	withFKs           bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PromptResponseQuery builder.
func (prq *PromptResponseQuery) Where(ps ...predicate.PromptResponse) *PromptResponseQuery {
	prq.predicates = append(prq.predicates, ps...)
	return prq
}

// Limit the number of records to be returned by this query.
func (prq *PromptResponseQuery) Limit(limit int) *PromptResponseQuery {
	prq.ctx.Limit = &limit
	return prq
}

// Offset to start from.
func (prq *PromptResponseQuery) Offset(offset int) *PromptResponseQuery {
	prq.ctx.Offset = &offset
	return prq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (prq *PromptResponseQuery) Unique(unique bool) *PromptResponseQuery {
	prq.ctx.Unique = &unique
	return prq
}

// Order specifies how the records should be ordered.
func (prq *PromptResponseQuery) Order(o ...promptresponse.OrderOption) *PromptResponseQuery {
	prq.order = append(prq.order, o...)
	return prq
}

// QueryPromptRequest chains the current query on the "prompt_request" edge.
func (prq *PromptResponseQuery) QueryPromptRequest() *PromptRequestQuery {
	query := (&PromptRequestClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(promptresponse.Table, promptresponse.FieldID, selector),
			sqlgraph.To(promptrequest.Table, promptrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, promptresponse.PromptRequestTable, promptresponse.PromptRequestColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PromptResponse entity from the query.
// Returns a *NotFoundError when no PromptResponse was found.
func (prq *PromptResponseQuery) First(ctx context.Context) (*PromptResponse, error) {
	nodes, err := prq.Limit(1).All(setContextOp(ctx, prq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{promptresponse.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (prq *PromptResponseQuery) FirstX(ctx context.Context) *PromptResponse {
	node, err := prq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PromptResponse ID from the query.
// Returns a *NotFoundError when no PromptResponse ID was found.
func (prq *PromptResponseQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = prq.Limit(1).IDs(setContextOp(ctx, prq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{promptresponse.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (prq *PromptResponseQuery) FirstIDX(ctx context.Context) int {
	id, err := prq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PromptResponse entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PromptResponse entity is found.
// Returns a *NotFoundError when no PromptResponse entities are found.
func (prq *PromptResponseQuery) Only(ctx context.Context) (*PromptResponse, error) {
	nodes, err := prq.Limit(2).All(setContextOp(ctx, prq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{promptresponse.Label}
	default:
		return nil, &NotSingularError{promptresponse.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (prq *PromptResponseQuery) OnlyX(ctx context.Context) *PromptResponse {
	node, err := prq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PromptResponse ID in the query.
// Returns a *NotSingularError when more than one PromptResponse ID is found.
// Returns a *NotFoundError when no entities are found.
func (prq *PromptResponseQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = prq.Limit(2).IDs(setContextOp(ctx, prq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{promptresponse.Label}
	default:
		err = &NotSingularError{promptresponse.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (prq *PromptResponseQuery) OnlyIDX(ctx context.Context) int {
	id, err := prq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PromptResponses.
func (prq *PromptResponseQuery) All(ctx context.Context) ([]*PromptResponse, error) {
	ctx = setContextOp(ctx, prq.ctx, "All")
	if err := prq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PromptResponse, *PromptResponseQuery]()
	return withInterceptors[[]*PromptResponse](ctx, prq, qr, prq.inters)
}

// AllX is like All, but panics if an error occurs.
func (prq *PromptResponseQuery) AllX(ctx context.Context) []*PromptResponse {
	nodes, err := prq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PromptResponse IDs.
func (prq *PromptResponseQuery) IDs(ctx context.Context) (ids []int, err error) {
	if prq.ctx.Unique == nil && prq.path != nil {
		prq.Unique(true)
	}
	ctx = setContextOp(ctx, prq.ctx, "IDs")
	if err = prq.Select(promptresponse.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (prq *PromptResponseQuery) IDsX(ctx context.Context) []int {
	ids, err := prq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (prq *PromptResponseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, prq.ctx, "Count")
	if err := prq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, prq, querierCount[*PromptResponseQuery](), prq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (prq *PromptResponseQuery) CountX(ctx context.Context) int {
	count, err := prq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (prq *PromptResponseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, prq.ctx, "Exist")
	switch _, err := prq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (prq *PromptResponseQuery) ExistX(ctx context.Context) bool {
	exist, err := prq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PromptResponseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (prq *PromptResponseQuery) Clone() *PromptResponseQuery {
	if prq == nil {
		return nil
	}
	return &PromptResponseQuery{
		config:            prq.config,
		ctx:               prq.ctx.Clone(),
		order:             append([]promptresponse.OrderOption{}, prq.order...),
		inters:            append([]Interceptor{}, prq.inters...),
		predicates:        append([]predicate.PromptResponse{}, prq.predicates...),
		withPromptRequest: prq.withPromptRequest.Clone(),
		// clone intermediate query.
		sql:  prq.sql.Clone(),
		path: prq.path,
	}
}

// WithPromptRequest tells the query-builder to eager-load the nodes that are connected to
// the "prompt_request" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PromptResponseQuery) WithPromptRequest(opts ...func(*PromptRequestQuery)) *PromptResponseQuery {
	query := (&PromptRequestClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withPromptRequest = query
	return prq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Response string `json:"response,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PromptResponse.Query().
//		GroupBy(promptresponse.FieldResponse).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (prq *PromptResponseQuery) GroupBy(field string, fields ...string) *PromptResponseGroupBy {
	prq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PromptResponseGroupBy{build: prq}
	grbuild.flds = &prq.ctx.Fields
	grbuild.label = promptresponse.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Response string `json:"response,omitempty"`
//	}
//
//	client.PromptResponse.Query().
//		Select(promptresponse.FieldResponse).
//		Scan(ctx, &v)
func (prq *PromptResponseQuery) Select(fields ...string) *PromptResponseSelect {
	prq.ctx.Fields = append(prq.ctx.Fields, fields...)
	sbuild := &PromptResponseSelect{PromptResponseQuery: prq}
	sbuild.label = promptresponse.Label
	sbuild.flds, sbuild.scan = &prq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PromptResponseSelect configured with the given aggregations.
func (prq *PromptResponseQuery) Aggregate(fns ...AggregateFunc) *PromptResponseSelect {
	return prq.Select().Aggregate(fns...)
}

func (prq *PromptResponseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range prq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, prq); err != nil {
				return err
			}
		}
	}
	for _, f := range prq.ctx.Fields {
		if !promptresponse.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if prq.path != nil {
		prev, err := prq.path(ctx)
		if err != nil {
			return err
		}
		prq.sql = prev
	}
	return nil
}

func (prq *PromptResponseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PromptResponse, error) {
	var (
		nodes       = []*PromptResponse{}
		withFKs     = prq.withFKs
		_spec       = prq.querySpec()
		loadedTypes = [1]bool{
			prq.withPromptRequest != nil,
		}
	)
	if prq.withPromptRequest != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, promptresponse.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PromptResponse).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PromptResponse{config: prq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, prq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := prq.withPromptRequest; query != nil {
		if err := prq.loadPromptRequest(ctx, query, nodes, nil,
			func(n *PromptResponse, e *PromptRequest) { n.Edges.PromptRequest = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (prq *PromptResponseQuery) loadPromptRequest(ctx context.Context, query *PromptRequestQuery, nodes []*PromptResponse, init func(*PromptResponse), assign func(*PromptResponse, *PromptRequest)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PromptResponse)
	for i := range nodes {
		if nodes[i].prompt_request_prompt_response == nil {
			continue
		}
		fk := *nodes[i].prompt_request_prompt_response
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(promptrequest.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "prompt_request_prompt_response" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (prq *PromptResponseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := prq.querySpec()
	_spec.Node.Columns = prq.ctx.Fields
	if len(prq.ctx.Fields) > 0 {
		_spec.Unique = prq.ctx.Unique != nil && *prq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, prq.driver, _spec)
}

func (prq *PromptResponseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(promptresponse.Table, promptresponse.Columns, sqlgraph.NewFieldSpec(promptresponse.FieldID, field.TypeInt))
	_spec.From = prq.sql
	if unique := prq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if prq.path != nil {
		_spec.Unique = true
	}
	if fields := prq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promptresponse.FieldID)
		for i := range fields {
			if fields[i] != promptresponse.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := prq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := prq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := prq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := prq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (prq *PromptResponseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(prq.driver.Dialect())
	t1 := builder.Table(promptresponse.Table)
	columns := prq.ctx.Fields
	if len(columns) == 0 {
		columns = promptresponse.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if prq.sql != nil {
		selector = prq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if prq.ctx.Unique != nil && *prq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range prq.predicates {
		p(selector)
	}
	for _, p := range prq.order {
		p(selector)
	}
	if offset := prq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := prq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PromptResponseGroupBy is the group-by builder for PromptResponse entities.
type PromptResponseGroupBy struct {
	selector
	build *PromptResponseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (prgb *PromptResponseGroupBy) Aggregate(fns ...AggregateFunc) *PromptResponseGroupBy {
	prgb.fns = append(prgb.fns, fns...)
	return prgb
}

// Scan applies the selector query and scans the result into the given value.
func (prgb *PromptResponseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prgb.build.ctx, "GroupBy")
	if err := prgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PromptResponseQuery, *PromptResponseGroupBy](ctx, prgb.build, prgb, prgb.build.inters, v)
}

func (prgb *PromptResponseGroupBy) sqlScan(ctx context.Context, root *PromptResponseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(prgb.fns))
	for _, fn := range prgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*prgb.flds)+len(prgb.fns))
		for _, f := range *prgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*prgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PromptResponseSelect is the builder for selecting fields of PromptResponse entities.
type PromptResponseSelect struct {
	*PromptResponseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (prs *PromptResponseSelect) Aggregate(fns ...AggregateFunc) *PromptResponseSelect {
	prs.fns = append(prs.fns, fns...)
	return prs
}

// Scan applies the selector query and scans the result into the given value.
func (prs *PromptResponseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prs.ctx, "Select")
	if err := prs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PromptResponseQuery, *PromptResponseSelect](ctx, prs.PromptResponseQuery, prs, prs.inters, v)
}

func (prs *PromptResponseSelect) sqlScan(ctx context.Context, root *PromptResponseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(prs.fns))
	for _, fn := range prs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*prs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
