// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PromptRequest is the predicate function for promptrequest builders.
type PromptRequest func(*sql.Selector)

// PromptResponse is the predicate function for promptresponse builders.
type PromptResponse func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
