// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PromptRequest is the predicate function for promptrequest builders.
type PromptRequest func(*sql.Selector)
